### ISSUE TITLE
qsts controller doesn't update sts volumeClaimTemplates

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/quarks-operator#1167]
**Describe the bug**

KubeCF recently changed the backing storage for the Diego ephemeral data from PVCs to emptyDir, which uses the nodes' local storage. Practically, when we do an upgrade, the controller should get rid of the `spec.volumeClaimTemplates` of the statefulset.

There are other implications in KubeCF while doing this, as I understand, the statefulset needs to be recreated, ultimately causing app downtime. This is not a concern of quarks-operator as it stands.

**To Reproduce**

Switch from PVC-backed ephemeral storage to the emptyDir-backed one, check that the pod respects the statefulset, which disrespects the quarks-statefulset.

**Expected behavior**

Even if it's not desirable (in the Diego cell's case - causing app downtime), it should do what the spec says.

**Environment**

quarks-operator version 6.1.8+0.g2821133a.

**Comment by manno** [comment]
@viovanov couldn't reproduce this. Maybe it was fixed by another bug fix.

**Comment by f0rmiga** [comment]
Reopening as this was not fixed. Ping @mook-as as he's also seeing the same behaviour.
