### ISSUE TITLE
Often getting multiple jobs after updating kubecf ops-files

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/quarks-operator#750]
When I apply a change, I usually get multiple `bpm` and `ig` jobs:

```
NAME                                READY   STATUS       RESTARTS   AGE
bpm-kubecf-31a221bf58edc585-26ps4   0/20    Init:24/30   0          65s
bpm-kubecf-bcd5e3c7eeb0a857-647cg   0/20    Init:21/30   0          52s
ig-kubecf-b7e2c93ab14bbdb3-kmrqp    0/20    Init:19/30   0          52s
ig-kubecf-e142d0c421e1f13d-cbddz    0/20    Init:23/30   0          65s
```

In this case, I simply changed the `cloud_controller_ng` properties:

```
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/security_group_definitions/-
  value:
    name: internal
    rules:
    - destination: {{ required "A valid 'kube.service_cluster_ip_range' is required!" .Values.kube.service_cluster_ip_range | quote }}
      protocol: all
    - destination: {{ required "A valid 'kube.pod_cluster_ip_range' is required!" .Values.kube.pod_cluster_ip_range | quote }}
      protocol: all
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_staging_security_groups/-
  value: internal
```

**Comment by manno** [comment]
Can you give me some steps to reproduce it? You added a new ops file and  referenced that from the bdpl resource? Or did you change and existing ops file?

Also if this happens again, can you dump the cf-operator log (optionally the quarks-job log, too)?

`kubectl logs -n test-cfo cf-operator` should be helpful.

**Comment by andreas-kupries** [comment]
Hi @manno - I attached logs I got when seeing the reported issue on a freshly created minikube install of kcf mine to the pivotal story. Full description of the setup to be found in file OPERATOR-ANOMALY.md in the tarball. I hope it helps.

**Comment by andreas-kupries** [comment]
Still true for cf-operator-v2.0.0-0.g0142d1e9.tgz in the head of kubecf.

**Comment by rohitsakala** [comment]
Fixed this with https://github.com/cloudfoundry-incubator/cf-operator/pull/797

**Comment by jandubois** [comment]
This still happens to me with the latest kubecf and cf-operator (4.3.1).

After adding a new db encryption key and running `bazel run //dev/kubecf:apply` I see first the `dm` job, followed by the new `ig` job. But after 30-50s I see yet another `dm` job while `ig` is still working through its init containers:

```
kubecf    dm-59e4b70710117d2a-rzqp4         0/2     Pending      0          7s
kubecf    ig-09c87482cba30eaa-zr2dm         0/22    Init:29/40   0          42s
```

In turn this will result in 2 `ig` jobs running in parallel:

```
kubecf    ig-09c87482cba30eaa-zr2dm         0/22    PodInitializing   0          72s
kubecf    ig-fea60cd62f4295c7-tjkfd         0/22    Init:0/40         0          5s
```

Eventually they all run to completion, and everything is fine, but it seems wrong that the operator creates 2 sets of jobs.

I've put the additional config file as well as the logs from the operator and the quarks job into a gist at https://gist.github.com/jandubois/8bf2f2d99f4b82d772d5863fedfc6e01

**Comment by jandubois** [comment]
Just for reference, the additional config values modify one of the included ops files, so I think I'm seeing the same issue, which is why I re-opened it:

https://github.com/cloudfoundry-incubator/kubecf/blob/2f2c222302d76af40039681c229aea78c2290a9b/deploy/helm/kubecf/assets/operations/instance_groups/api.yaml#L98-L124

**Comment by jandubois** [comment]
Oh, and this is reproducible every single time, in case you want to observe it yourself.

**Comment by viovanov** [comment]
@manno perhaps we need a larger meltdown window?
We'll need to see which 2 updates result in 2 separate IGs ..

**Comment by jandubois** [comment]
Not sure if this is relevant, but the ops file change will eventually update 3 pods: api, cc-worker, and scheduler. All other pods are unaffected.

**Comment by mudler** [comment]
I've tried to reproduce this, and I can reproduce it always also by trying to downgrade from KubeCF v2.1.0 to v2.0.0. After the first Ig is created, a new dm pops up and I can see two instance groups running in parallel

**Comment by jandubois** [comment]
Just for another repro scenario, I just deployed KubeCF with Diego, ran smoke tests, and then updated to using Eirini.

I see 4 (four) ig jobs running currently, and also 3 running and 3 completed `database-seeder` jobs.

**Comment by rohitsakala** [comment]
Hi @f0rmiga 

The multiple dm job issue should be fixed with https://github.com/cloudfoundry-incubator/quarks-operator/pull/1020. I checked it with upgrading Autoscaler issue on cf-operator master and kubecf v2.2.0.  Please re-open if you still face the issue.
